CREATE FILE FORMAT AIRBNB.RAW.CSV_GZ
  TYPE = 'CSV'
  COMPRESSION = 'GZIP'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'  
  SKIP_HEADER = 1
  NULL_IF = ('', 'N/A', 'NULL')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE STAGE AIRBNB.RAW.S3_RAW
  STORAGE_INTEGRATION = s3_airbnb_int
  URL = 's3://chicago-airbnb/raw/'
  FILE_FORMAT = AIRBNB.RAW.CSV_GZ;

LIST @AIRBNB.RAW.S3_RAW;
