CREATE ROLE IF NOT EXISTS DBT_ROLE;

GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE AIRBNB TO ROLE DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE AIRBNB TO ROLE DBT_ROLE;    
GRANT USAGE ON SCHEMA AIRBNB.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA AIRBNB.RAW TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AIRBNB.RAW TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA AIRBNB.AUDIT TO ROLE DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA AIRBNB.AUDIT TO ROLE DBT_ROLE;

CREATE USER IF NOT EXISTS DBT_USER
  PASSWORD = 'password'
  DEFAULT_ROLE = DBT_ROLE
  DEFAULT_WAREHOUSE = TRANSFORM_WH;
GRANT ROLE DBT_ROLE TO USER DBT_USER;